/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestScenariosRouteImport } from './routes/test-scenarios'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PinnedRouteImport } from './routes/pinned'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as FixSessionsRouteImport } from './routes/fix-sessions'
import { Route as CreateIssueRouteImport } from './routes/create-issue'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestScenariosIndexRouteImport } from './routes/test-scenarios.index'
import { Route as SpecsIndexRouteImport } from './routes/specs.index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as TestScenariosIdRouteImport } from './routes/test-scenarios.$id'
import { Route as RecordingsIdRouteImport } from './routes/recordings.$id'
import { Route as IssuesProjectIdIidRouteImport } from './routes/issues.$projectId.$iid'

const TestScenariosRoute = TestScenariosRouteImport.update({
  id: '/test-scenarios',
  path: '/test-scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PinnedRoute = PinnedRouteImport.update({
  id: '/pinned',
  path: '/pinned',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const FixSessionsRoute = FixSessionsRouteImport.update({
  id: '/fix-sessions',
  path: '/fix-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIssueRoute = CreateIssueRouteImport.update({
  id: '/create-issue',
  path: '/create-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestScenariosIndexRoute = TestScenariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestScenariosRoute,
} as any)
const SpecsIndexRoute = SpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecsRoute,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const TestScenariosIdRoute = TestScenariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestScenariosRoute,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const IssuesProjectIdIidRoute = IssuesProjectIdIidRouteImport.update({
  id: '/$projectId/$iid',
  path: '/$projectId/$iid',
  getParentRoute: () => IssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/create-issue': typeof CreateIssueRoute
  '/fix-sessions': typeof FixSessionsRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/pinned': typeof PinnedRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/test-scenarios': typeof TestScenariosRouteWithChildren
  '/recordings/$id': typeof RecordingsIdRoute
  '/test-scenarios/$id': typeof TestScenariosIdRoute
  '/issues/': typeof IssuesIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/test-scenarios/': typeof TestScenariosIndexRoute
  '/issues/$projectId/$iid': typeof IssuesProjectIdIidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/create-issue': typeof CreateIssueRoute
  '/fix-sessions': typeof FixSessionsRoute
  '/login': typeof LoginRoute
  '/pinned': typeof PinnedRoute
  '/profile': typeof ProfileRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/test-scenarios/$id': typeof TestScenariosIdRoute
  '/issues': typeof IssuesIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/specs': typeof SpecsIndexRoute
  '/test-scenarios': typeof TestScenariosIndexRoute
  '/issues/$projectId/$iid': typeof IssuesProjectIdIidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/create-issue': typeof CreateIssueRoute
  '/fix-sessions': typeof FixSessionsRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/pinned': typeof PinnedRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/test-scenarios': typeof TestScenariosRouteWithChildren
  '/recordings/$id': typeof RecordingsIdRoute
  '/test-scenarios/$id': typeof TestScenariosIdRoute
  '/issues/': typeof IssuesIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/test-scenarios/': typeof TestScenariosIndexRoute
  '/issues/$projectId/$iid': typeof IssuesProjectIdIidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/create-issue'
    | '/fix-sessions'
    | '/issues'
    | '/login'
    | '/pinned'
    | '/profile'
    | '/recordings'
    | '/specs'
    | '/test-scenarios'
    | '/recordings/$id'
    | '/test-scenarios/$id'
    | '/issues/'
    | '/recordings/'
    | '/specs/'
    | '/test-scenarios/'
    | '/issues/$projectId/$iid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/create-issue'
    | '/fix-sessions'
    | '/login'
    | '/pinned'
    | '/profile'
    | '/recordings/$id'
    | '/test-scenarios/$id'
    | '/issues'
    | '/recordings'
    | '/specs'
    | '/test-scenarios'
    | '/issues/$projectId/$iid'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/create-issue'
    | '/fix-sessions'
    | '/issues'
    | '/login'
    | '/pinned'
    | '/profile'
    | '/recordings'
    | '/specs'
    | '/test-scenarios'
    | '/recordings/$id'
    | '/test-scenarios/$id'
    | '/issues/'
    | '/recordings/'
    | '/specs/'
    | '/test-scenarios/'
    | '/issues/$projectId/$iid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  CreateIssueRoute: typeof CreateIssueRoute
  FixSessionsRoute: typeof FixSessionsRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PinnedRoute: typeof PinnedRoute
  ProfileRoute: typeof ProfileRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  SpecsRoute: typeof SpecsRouteWithChildren
  TestScenariosRoute: typeof TestScenariosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-scenarios': {
      id: '/test-scenarios'
      path: '/test-scenarios'
      fullPath: '/test-scenarios'
      preLoaderRoute: typeof TestScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinned': {
      id: '/pinned'
      path: '/pinned'
      fullPath: '/pinned'
      preLoaderRoute: typeof PinnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-sessions': {
      id: '/fix-sessions'
      path: '/fix-sessions'
      fullPath: '/fix-sessions'
      preLoaderRoute: typeof FixSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-issue': {
      id: '/create-issue'
      path: '/create-issue'
      fullPath: '/create-issue'
      preLoaderRoute: typeof CreateIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-scenarios/': {
      id: '/test-scenarios/'
      path: '/'
      fullPath: '/test-scenarios/'
      preLoaderRoute: typeof TestScenariosIndexRouteImport
      parentRoute: typeof TestScenariosRoute
    }
    '/specs/': {
      id: '/specs/'
      path: '/'
      fullPath: '/specs/'
      preLoaderRoute: typeof SpecsIndexRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/test-scenarios/$id': {
      id: '/test-scenarios/$id'
      path: '/$id'
      fullPath: '/test-scenarios/$id'
      preLoaderRoute: typeof TestScenariosIdRouteImport
      parentRoute: typeof TestScenariosRoute
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/issues/$projectId/$iid': {
      id: '/issues/$projectId/$iid'
      path: '/$projectId/$iid'
      fullPath: '/issues/$projectId/$iid'
      preLoaderRoute: typeof IssuesProjectIdIidRouteImport
      parentRoute: typeof IssuesRoute
    }
  }
}

interface IssuesRouteChildren {
  IssuesIndexRoute: typeof IssuesIndexRoute
  IssuesProjectIdIidRoute: typeof IssuesProjectIdIidRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIndexRoute: IssuesIndexRoute,
  IssuesProjectIdIidRoute: IssuesProjectIdIidRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

interface SpecsRouteChildren {
  SpecsIndexRoute: typeof SpecsIndexRoute
}

const SpecsRouteChildren: SpecsRouteChildren = {
  SpecsIndexRoute: SpecsIndexRoute,
}

const SpecsRouteWithChildren = SpecsRoute._addFileChildren(SpecsRouteChildren)

interface TestScenariosRouteChildren {
  TestScenariosIdRoute: typeof TestScenariosIdRoute
  TestScenariosIndexRoute: typeof TestScenariosIndexRoute
}

const TestScenariosRouteChildren: TestScenariosRouteChildren = {
  TestScenariosIdRoute: TestScenariosIdRoute,
  TestScenariosIndexRoute: TestScenariosIndexRoute,
}

const TestScenariosRouteWithChildren = TestScenariosRoute._addFileChildren(
  TestScenariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  CreateIssueRoute: CreateIssueRoute,
  FixSessionsRoute: FixSessionsRoute,
  IssuesRoute: IssuesRouteWithChildren,
  LoginRoute: LoginRoute,
  PinnedRoute: PinnedRoute,
  ProfileRoute: ProfileRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  SpecsRoute: SpecsRouteWithChildren,
  TestScenariosRoute: TestScenariosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
