/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestScenariosRouteImport } from './routes/test-scenarios'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PinnedRouteImport } from './routes/pinned'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as FixSessionsRouteImport } from './routes/fix-sessions'
import { Route as CreateIssueRouteImport } from './routes/create-issue'
import { Route as ChatSessionsRouteImport } from './routes/chat-sessions'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestScenariosIndexRouteImport } from './routes/test-scenarios.index'
import { Route as SpecsIndexRouteImport } from './routes/specs.index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as ChatSessionsIndexRouteImport } from './routes/chat-sessions.index'
import { Route as TestScenariosIdRouteImport } from './routes/test-scenarios.$id'
import { Route as RecordingsIdRouteImport } from './routes/recordings.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ChatSessionsSessionIdRouteImport } from './routes/chat-sessions.$sessionId'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as ProjectsIdTestScenariosRouteImport } from './routes/projects.$id.test-scenarios'
import { Route as ProjectsIdSpecsRouteImport } from './routes/projects.$id.specs'
import { Route as ProjectsIdSettingsRouteImport } from './routes/projects.$id.settings'
import { Route as ProjectsIdRecordingsRouteImport } from './routes/projects.$id.recordings'
import { Route as ProjectsIdIssuesRouteImport } from './routes/projects.$id.issues'
import { Route as ProjectsIdFixSessionsRouteImport } from './routes/projects.$id.fix-sessions'
import { Route as ProjectsIdBoardsRouteImport } from './routes/projects.$id.boards'
import { Route as IssuesProjectIdIidRouteImport } from './routes/issues.$projectId.$iid'
import { Route as ProjectsIdTestScenariosScenarioIdRouteImport } from './routes/projects.$id.test-scenarios.$scenarioId'
import { Route as ProjectsIdIssuesIidRouteImport } from './routes/projects.$id.issues.$iid'

const TestScenariosRoute = TestScenariosRouteImport.update({
  id: '/test-scenarios',
  path: '/test-scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PinnedRoute = PinnedRouteImport.update({
  id: '/pinned',
  path: '/pinned',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const FixSessionsRoute = FixSessionsRouteImport.update({
  id: '/fix-sessions',
  path: '/fix-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIssueRoute = CreateIssueRouteImport.update({
  id: '/create-issue',
  path: '/create-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionsRoute = ChatSessionsRouteImport.update({
  id: '/chat-sessions',
  path: '/chat-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestScenariosIndexRoute = TestScenariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestScenariosRoute,
} as any)
const SpecsIndexRoute = SpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecsRoute,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const ChatSessionsIndexRoute = ChatSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatSessionsRoute,
} as any)
const TestScenariosIdRoute = TestScenariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestScenariosRoute,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ChatSessionsSessionIdRoute = ChatSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatSessionsRoute,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdTestScenariosRoute = ProjectsIdTestScenariosRouteImport.update({
  id: '/test-scenarios',
  path: '/test-scenarios',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdSpecsRoute = ProjectsIdSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdSettingsRoute = ProjectsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdRecordingsRoute = ProjectsIdRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdIssuesRoute = ProjectsIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdFixSessionsRoute = ProjectsIdFixSessionsRouteImport.update({
  id: '/fix-sessions',
  path: '/fix-sessions',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdBoardsRoute = ProjectsIdBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const IssuesProjectIdIidRoute = IssuesProjectIdIidRouteImport.update({
  id: '/$projectId/$iid',
  path: '/$projectId/$iid',
  getParentRoute: () => IssuesRoute,
} as any)
const ProjectsIdTestScenariosScenarioIdRoute =
  ProjectsIdTestScenariosScenarioIdRouteImport.update({
    id: '/$scenarioId',
    path: '/$scenarioId',
    getParentRoute: () => ProjectsIdTestScenariosRoute,
  } as any)
const ProjectsIdIssuesIidRoute = ProjectsIdIssuesIidRouteImport.update({
  id: '/$iid',
  path: '/$iid',
  getParentRoute: () => ProjectsIdIssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/chat-sessions': typeof ChatSessionsRouteWithChildren
  '/create-issue': typeof CreateIssueRoute
  '/fix-sessions': typeof FixSessionsRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/pinned': typeof PinnedRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recordings': typeof RecordingsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/test-scenarios': typeof TestScenariosRouteWithChildren
  '/chat-sessions/$sessionId': typeof ChatSessionsSessionIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/recordings/$id': typeof RecordingsIdRoute
  '/test-scenarios/$id': typeof TestScenariosIdRoute
  '/chat-sessions/': typeof ChatSessionsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/test-scenarios/': typeof TestScenariosIndexRoute
  '/issues/$projectId/$iid': typeof IssuesProjectIdIidRoute
  '/projects/$id/boards': typeof ProjectsIdBoardsRoute
  '/projects/$id/fix-sessions': typeof ProjectsIdFixSessionsRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRouteWithChildren
  '/projects/$id/recordings': typeof ProjectsIdRecordingsRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/projects/$id/specs': typeof ProjectsIdSpecsRoute
  '/projects/$id/test-scenarios': typeof ProjectsIdTestScenariosRouteWithChildren
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/issues/$iid': typeof ProjectsIdIssuesIidRoute
  '/projects/$id/test-scenarios/$scenarioId': typeof ProjectsIdTestScenariosScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/create-issue': typeof CreateIssueRoute
  '/fix-sessions': typeof FixSessionsRoute
  '/login': typeof LoginRoute
  '/pinned': typeof PinnedRoute
  '/profile': typeof ProfileRoute
  '/chat-sessions/$sessionId': typeof ChatSessionsSessionIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/test-scenarios/$id': typeof TestScenariosIdRoute
  '/chat-sessions': typeof ChatSessionsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/specs': typeof SpecsIndexRoute
  '/test-scenarios': typeof TestScenariosIndexRoute
  '/issues/$projectId/$iid': typeof IssuesProjectIdIidRoute
  '/projects/$id/boards': typeof ProjectsIdBoardsRoute
  '/projects/$id/fix-sessions': typeof ProjectsIdFixSessionsRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRouteWithChildren
  '/projects/$id/recordings': typeof ProjectsIdRecordingsRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/projects/$id/specs': typeof ProjectsIdSpecsRoute
  '/projects/$id/test-scenarios': typeof ProjectsIdTestScenariosRouteWithChildren
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/issues/$iid': typeof ProjectsIdIssuesIidRoute
  '/projects/$id/test-scenarios/$scenarioId': typeof ProjectsIdTestScenariosScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/chat-sessions': typeof ChatSessionsRouteWithChildren
  '/create-issue': typeof CreateIssueRoute
  '/fix-sessions': typeof FixSessionsRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/pinned': typeof PinnedRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recordings': typeof RecordingsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/test-scenarios': typeof TestScenariosRouteWithChildren
  '/chat-sessions/$sessionId': typeof ChatSessionsSessionIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/recordings/$id': typeof RecordingsIdRoute
  '/test-scenarios/$id': typeof TestScenariosIdRoute
  '/chat-sessions/': typeof ChatSessionsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/test-scenarios/': typeof TestScenariosIndexRoute
  '/issues/$projectId/$iid': typeof IssuesProjectIdIidRoute
  '/projects/$id/boards': typeof ProjectsIdBoardsRoute
  '/projects/$id/fix-sessions': typeof ProjectsIdFixSessionsRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRouteWithChildren
  '/projects/$id/recordings': typeof ProjectsIdRecordingsRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/projects/$id/specs': typeof ProjectsIdSpecsRoute
  '/projects/$id/test-scenarios': typeof ProjectsIdTestScenariosRouteWithChildren
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/issues/$iid': typeof ProjectsIdIssuesIidRoute
  '/projects/$id/test-scenarios/$scenarioId': typeof ProjectsIdTestScenariosScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/chat-sessions'
    | '/create-issue'
    | '/fix-sessions'
    | '/issues'
    | '/login'
    | '/pinned'
    | '/profile'
    | '/projects'
    | '/recordings'
    | '/specs'
    | '/test-scenarios'
    | '/chat-sessions/$sessionId'
    | '/projects/$id'
    | '/recordings/$id'
    | '/test-scenarios/$id'
    | '/chat-sessions/'
    | '/issues/'
    | '/projects/'
    | '/recordings/'
    | '/specs/'
    | '/test-scenarios/'
    | '/issues/$projectId/$iid'
    | '/projects/$id/boards'
    | '/projects/$id/fix-sessions'
    | '/projects/$id/issues'
    | '/projects/$id/recordings'
    | '/projects/$id/settings'
    | '/projects/$id/specs'
    | '/projects/$id/test-scenarios'
    | '/projects/$id/'
    | '/projects/$id/issues/$iid'
    | '/projects/$id/test-scenarios/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/create-issue'
    | '/fix-sessions'
    | '/login'
    | '/pinned'
    | '/profile'
    | '/chat-sessions/$sessionId'
    | '/recordings/$id'
    | '/test-scenarios/$id'
    | '/chat-sessions'
    | '/issues'
    | '/projects'
    | '/recordings'
    | '/specs'
    | '/test-scenarios'
    | '/issues/$projectId/$iid'
    | '/projects/$id/boards'
    | '/projects/$id/fix-sessions'
    | '/projects/$id/issues'
    | '/projects/$id/recordings'
    | '/projects/$id/settings'
    | '/projects/$id/specs'
    | '/projects/$id/test-scenarios'
    | '/projects/$id'
    | '/projects/$id/issues/$iid'
    | '/projects/$id/test-scenarios/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/chat-sessions'
    | '/create-issue'
    | '/fix-sessions'
    | '/issues'
    | '/login'
    | '/pinned'
    | '/profile'
    | '/projects'
    | '/recordings'
    | '/specs'
    | '/test-scenarios'
    | '/chat-sessions/$sessionId'
    | '/projects/$id'
    | '/recordings/$id'
    | '/test-scenarios/$id'
    | '/chat-sessions/'
    | '/issues/'
    | '/projects/'
    | '/recordings/'
    | '/specs/'
    | '/test-scenarios/'
    | '/issues/$projectId/$iid'
    | '/projects/$id/boards'
    | '/projects/$id/fix-sessions'
    | '/projects/$id/issues'
    | '/projects/$id/recordings'
    | '/projects/$id/settings'
    | '/projects/$id/specs'
    | '/projects/$id/test-scenarios'
    | '/projects/$id/'
    | '/projects/$id/issues/$iid'
    | '/projects/$id/test-scenarios/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  ChatSessionsRoute: typeof ChatSessionsRouteWithChildren
  CreateIssueRoute: typeof CreateIssueRoute
  FixSessionsRoute: typeof FixSessionsRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PinnedRoute: typeof PinnedRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RecordingsRoute: typeof RecordingsRouteWithChildren
  SpecsRoute: typeof SpecsRouteWithChildren
  TestScenariosRoute: typeof TestScenariosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-scenarios': {
      id: '/test-scenarios'
      path: '/test-scenarios'
      fullPath: '/test-scenarios'
      preLoaderRoute: typeof TestScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinned': {
      id: '/pinned'
      path: '/pinned'
      fullPath: '/pinned'
      preLoaderRoute: typeof PinnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-sessions': {
      id: '/fix-sessions'
      path: '/fix-sessions'
      fullPath: '/fix-sessions'
      preLoaderRoute: typeof FixSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-issue': {
      id: '/create-issue'
      path: '/create-issue'
      fullPath: '/create-issue'
      preLoaderRoute: typeof CreateIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-sessions': {
      id: '/chat-sessions'
      path: '/chat-sessions'
      fullPath: '/chat-sessions'
      preLoaderRoute: typeof ChatSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-scenarios/': {
      id: '/test-scenarios/'
      path: '/'
      fullPath: '/test-scenarios/'
      preLoaderRoute: typeof TestScenariosIndexRouteImport
      parentRoute: typeof TestScenariosRoute
    }
    '/specs/': {
      id: '/specs/'
      path: '/'
      fullPath: '/specs/'
      preLoaderRoute: typeof SpecsIndexRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/chat-sessions/': {
      id: '/chat-sessions/'
      path: '/'
      fullPath: '/chat-sessions/'
      preLoaderRoute: typeof ChatSessionsIndexRouteImport
      parentRoute: typeof ChatSessionsRoute
    }
    '/test-scenarios/$id': {
      id: '/test-scenarios/$id'
      path: '/$id'
      fullPath: '/test-scenarios/$id'
      preLoaderRoute: typeof TestScenariosIdRouteImport
      parentRoute: typeof TestScenariosRoute
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/chat-sessions/$sessionId': {
      id: '/chat-sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat-sessions/$sessionId'
      preLoaderRoute: typeof ChatSessionsSessionIdRouteImport
      parentRoute: typeof ChatSessionsRoute
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/test-scenarios': {
      id: '/projects/$id/test-scenarios'
      path: '/test-scenarios'
      fullPath: '/projects/$id/test-scenarios'
      preLoaderRoute: typeof ProjectsIdTestScenariosRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/specs': {
      id: '/projects/$id/specs'
      path: '/specs'
      fullPath: '/projects/$id/specs'
      preLoaderRoute: typeof ProjectsIdSpecsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/settings': {
      id: '/projects/$id/settings'
      path: '/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof ProjectsIdSettingsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/recordings': {
      id: '/projects/$id/recordings'
      path: '/recordings'
      fullPath: '/projects/$id/recordings'
      preLoaderRoute: typeof ProjectsIdRecordingsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/issues': {
      id: '/projects/$id/issues'
      path: '/issues'
      fullPath: '/projects/$id/issues'
      preLoaderRoute: typeof ProjectsIdIssuesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/fix-sessions': {
      id: '/projects/$id/fix-sessions'
      path: '/fix-sessions'
      fullPath: '/projects/$id/fix-sessions'
      preLoaderRoute: typeof ProjectsIdFixSessionsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/boards': {
      id: '/projects/$id/boards'
      path: '/boards'
      fullPath: '/projects/$id/boards'
      preLoaderRoute: typeof ProjectsIdBoardsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/issues/$projectId/$iid': {
      id: '/issues/$projectId/$iid'
      path: '/$projectId/$iid'
      fullPath: '/issues/$projectId/$iid'
      preLoaderRoute: typeof IssuesProjectIdIidRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/projects/$id/test-scenarios/$scenarioId': {
      id: '/projects/$id/test-scenarios/$scenarioId'
      path: '/$scenarioId'
      fullPath: '/projects/$id/test-scenarios/$scenarioId'
      preLoaderRoute: typeof ProjectsIdTestScenariosScenarioIdRouteImport
      parentRoute: typeof ProjectsIdTestScenariosRoute
    }
    '/projects/$id/issues/$iid': {
      id: '/projects/$id/issues/$iid'
      path: '/$iid'
      fullPath: '/projects/$id/issues/$iid'
      preLoaderRoute: typeof ProjectsIdIssuesIidRouteImport
      parentRoute: typeof ProjectsIdIssuesRoute
    }
  }
}

interface ChatSessionsRouteChildren {
  ChatSessionsSessionIdRoute: typeof ChatSessionsSessionIdRoute
  ChatSessionsIndexRoute: typeof ChatSessionsIndexRoute
}

const ChatSessionsRouteChildren: ChatSessionsRouteChildren = {
  ChatSessionsSessionIdRoute: ChatSessionsSessionIdRoute,
  ChatSessionsIndexRoute: ChatSessionsIndexRoute,
}

const ChatSessionsRouteWithChildren = ChatSessionsRoute._addFileChildren(
  ChatSessionsRouteChildren,
)

interface IssuesRouteChildren {
  IssuesIndexRoute: typeof IssuesIndexRoute
  IssuesProjectIdIidRoute: typeof IssuesProjectIdIidRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIndexRoute: IssuesIndexRoute,
  IssuesProjectIdIidRoute: IssuesProjectIdIidRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface ProjectsIdIssuesRouteChildren {
  ProjectsIdIssuesIidRoute: typeof ProjectsIdIssuesIidRoute
}

const ProjectsIdIssuesRouteChildren: ProjectsIdIssuesRouteChildren = {
  ProjectsIdIssuesIidRoute: ProjectsIdIssuesIidRoute,
}

const ProjectsIdIssuesRouteWithChildren =
  ProjectsIdIssuesRoute._addFileChildren(ProjectsIdIssuesRouteChildren)

interface ProjectsIdTestScenariosRouteChildren {
  ProjectsIdTestScenariosScenarioIdRoute: typeof ProjectsIdTestScenariosScenarioIdRoute
}

const ProjectsIdTestScenariosRouteChildren: ProjectsIdTestScenariosRouteChildren =
  {
    ProjectsIdTestScenariosScenarioIdRoute:
      ProjectsIdTestScenariosScenarioIdRoute,
  }

const ProjectsIdTestScenariosRouteWithChildren =
  ProjectsIdTestScenariosRoute._addFileChildren(
    ProjectsIdTestScenariosRouteChildren,
  )

interface ProjectsIdRouteChildren {
  ProjectsIdBoardsRoute: typeof ProjectsIdBoardsRoute
  ProjectsIdFixSessionsRoute: typeof ProjectsIdFixSessionsRoute
  ProjectsIdIssuesRoute: typeof ProjectsIdIssuesRouteWithChildren
  ProjectsIdRecordingsRoute: typeof ProjectsIdRecordingsRoute
  ProjectsIdSettingsRoute: typeof ProjectsIdSettingsRoute
  ProjectsIdSpecsRoute: typeof ProjectsIdSpecsRoute
  ProjectsIdTestScenariosRoute: typeof ProjectsIdTestScenariosRouteWithChildren
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdBoardsRoute: ProjectsIdBoardsRoute,
  ProjectsIdFixSessionsRoute: ProjectsIdFixSessionsRoute,
  ProjectsIdIssuesRoute: ProjectsIdIssuesRouteWithChildren,
  ProjectsIdRecordingsRoute: ProjectsIdRecordingsRoute,
  ProjectsIdSettingsRoute: ProjectsIdSettingsRoute,
  ProjectsIdSpecsRoute: ProjectsIdSpecsRoute,
  ProjectsIdTestScenariosRoute: ProjectsIdTestScenariosRouteWithChildren,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

interface SpecsRouteChildren {
  SpecsIndexRoute: typeof SpecsIndexRoute
}

const SpecsRouteChildren: SpecsRouteChildren = {
  SpecsIndexRoute: SpecsIndexRoute,
}

const SpecsRouteWithChildren = SpecsRoute._addFileChildren(SpecsRouteChildren)

interface TestScenariosRouteChildren {
  TestScenariosIdRoute: typeof TestScenariosIdRoute
  TestScenariosIndexRoute: typeof TestScenariosIndexRoute
}

const TestScenariosRouteChildren: TestScenariosRouteChildren = {
  TestScenariosIdRoute: TestScenariosIdRoute,
  TestScenariosIndexRoute: TestScenariosIndexRoute,
}

const TestScenariosRouteWithChildren = TestScenariosRoute._addFileChildren(
  TestScenariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  ChatSessionsRoute: ChatSessionsRouteWithChildren,
  CreateIssueRoute: CreateIssueRoute,
  FixSessionsRoute: FixSessionsRoute,
  IssuesRoute: IssuesRouteWithChildren,
  LoginRoute: LoginRoute,
  PinnedRoute: PinnedRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RecordingsRoute: RecordingsRouteWithChildren,
  SpecsRoute: SpecsRouteWithChildren,
  TestScenariosRoute: TestScenariosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
